framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            amqp: "amqp://guest:guest@localhost:5672/%2f/advice"


        routing:
            # Route your messages to the transports
            'App\Message\MyMessage': amqp
